services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trailblazer'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=trailblazer'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=trailblazer'
    ports:
      - '5672:5672'
