services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trailblazer'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=trailblazer'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=trailblazer'
    ports:
      - '5672:5672'
      - '15672:15672'
  keycloak:
    image: 'keycloak/keycloak:latest'
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev', '--import-realm']
    volumes:
      - ./keycloak:/tmp/keycloak
      - ./keycloak/realms:/opt/keycloak/data/import
