services:
  race-producer:
    image: raceproducer:0.0.1-SNAPSHOT
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_trailblazer_producer_db:5432/trailblazer'
      - 'SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/trailblazer'
      - 'LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG'
    ports:
      - '8081:8080'
  race-consumer:
    image: raceconsumer:0.0.1-SNAPSHOT
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_trailblazer_consumer_db:5432/trailblazer'
      - 'SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/trailblazer'
      - 'LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG'
    ports:
      - '8082:8080'
  postgres_trailblazer_producer_db:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=trailblazer'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=trailblazer'
    ports:
      - '5432:5432'
  postgres_trailblazer_consumer_db:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=trailblazer'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=trailblazer'
    ports:
      - '5433:5432'
  rabbitmq:
    image: 'rabbitmq:3.13.2-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=trailblazer'
    ports:
      - '5672:5672'
      - '15672:15672'
  keycloak:
    image: 'keycloak/keycloak:24.0'
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev', '--import-realm']
    volumes:
      - ./keycloak:/tmp/keycloak
      - ./keycloak/realms:/opt/keycloak/data/import
