spring:
  application:
    name: raceproducer
  datasource:
    url: jdbc:postgresql://localhost:5432/trailblazer
    username: trailblazer
    password: secret
  rabbitmq:
    username: trailblazer
    password: secret
    host: localhost
    port: 5672
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

rabbitmq:
    queue:
      name: "trailblazer-queue"
    exchange:
      name: "trailblazer-exchange"
    routing:
      key: "routing_key"
