spring:
  application:
    name: raceconsumer
  rabbitmq:
    username: trailblazer
    password: secret
    host: localhost
    port: 5672

rabbitmq:
  queue:
    name: "trailblazer-queue"
  exchange:
    name: "trailblazer-exchange"
  routing:
    key: "routing_key"
server:
  port: 8081
