spring:
  application:
    name: raceconsumer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/trailblazer
  datasource:
    url: jdbc:postgresql://localhost:5433/trailblazer
    username: trailblazer
    password: secret
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 3
          max-interval: 1s
    username: trailblazer
    password: secret
    host: localhost
    port: 5672
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    default-schema: public

rabbitmq:
  queue:
    name: "trailblazer-queue"
  exchange:
    name: "trailblazer-exchange"
  routing:
    key: "routing_key"
server:
  port: 8082
